const menuButton=document.querySelector('.menu-button');const menu=document.querySelector('.menu-overlay');const closeButton=document.querySelector('.close-menu');const menuLinks=document.querySelectorAll('.menu-overlay a');function openMenu(){menu.classList.add('open');menu.setAttribute('aria-hidden','false');menuButton.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'}function closeMenu(){menu.classList.remove('open');menu.setAttribute('aria-hidden','true');menuButton.setAttribute('aria-expanded','false');document.body.style.overflow=''}menuButton.addEventListener('click',openMenu);closeButton.addEventListener('click',closeMenu);menuLinks.forEach(link=>link.addEventListener('click',closeMenu));

const mobilePageStyle=document.createElement('style');mobilePageStyle.textContent=`@media(max-width:700px){body{height:100svh;overflow:hidden}body,main#top{overscroll-behavior:none}main#top{position:relative;height:100svh;overflow:hidden}.site-header{position:fixed;top:0;left:0;right:0;z-index:50}.hero,.collection-section{position:absolute!important;top:0;left:0;width:100%;height:100svh!important;min-height:0!important;margin:0!important;transition:transform .62s cubic-bezier(.22,.61,.36,1);will-change:transform;overflow:hidden}.hero{transform:translate3d(0,0,0);padding-top:56px!important}.collection-section{transform:translate3d(100%,0,0);padding-top:56px!important;overflow:hidden}.hero-image{inset:56px 0 0!important;height:calc(100% - 56px)!important}.hero-copy{z-index:4}.hero-footer{z-index:5}.collection-intro{z-index:4}.collection-grid{margin-top:76px!important}.collection-brand{margin-top:36px!important}.collection-bottom{margin-top:33px!important}body.page-two .hero{transform:translate3d(-100%,0,0)}body.page-two .collection-section{transform:translate3d(0,0,0)}body.swipe-lock .hero,body.swipe-lock .collection-section{transition:none}.menu-overlay{z-index:100}}`;document.head.appendChild(mobilePageStyle);

let currentPage=1;let startX=0;let startY=0;let tracking=false;let moved=false;const SWIPE_DISTANCE=38;
function showPage(page){currentPage=page;document.body.classList.toggle('page-two',page===2);document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';if(page===1){history.replaceState(null,'','#top')}else{history.replaceState(null,'','#collection')}}
function handleSwipeEnd(x,y){if(!tracking||menu.classList.contains('open'))return;tracking=false;const dx=x-startX,dy=y-startY;if(Math.max(Math.abs(dx),Math.abs(dy))<SWIPE_DISTANCE)return;showPage(currentPage===1?2:1)}
document.addEventListener('touchstart',e=>{if(!e.touches.length||menu.classList.contains('open'))return;startX=e.touches[0].clientX;startY=e.touches[0].clientY;tracking=true;moved=false},{passive:true});document.addEventListener('touchmove',e=>{if(!tracking)return;const t=e.touches[0];if(Math.max(Math.abs(t.clientX-startX),Math.abs(t.clientY-startY))>8)moved=true},{passive:true});document.addEventListener('touchend',e=>{if(!tracking)return;const t=e.changedTouches[0];handleSwipeEnd(t.clientX,t.clientY)},{passive:true});

document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen')return;if(menu.classList.contains('open'))return;startX=e.clientX;startY=e.clientY;tracking=true},{passive:true});document.addEventListener('pointerup',e=>{if(e.pointerType==='touch'||e.pointerType==='pen')return;handleSwipeEnd(e.clientX,e.clientY)});

document.querySelectorAll('a[href="#collection"]').forEach(link=>link.addEventListener('click',e=>{if(window.matchMedia('(max-width:700px)').matches){e.preventDefault();showPage(2)}}));document.querySelectorAll('a[href="#top"]').forEach(link=>link.addEventListener('click',e=>{if(window.matchMedia('(max-width:700px)').matches){e.preventDefault();showPage(1)}}));
window.addEventListener('resize',()=>{if(!window.matchMedia('(max-width:700px)').matches){document.body.classList.remove('page-two');document.documentElement.style.overflow='';document.body.style.overflow=''}});
showPage(1);